
@startuml

skinparam classFontColor 007BFF
skinparam classFontSize 12
skinparam classFontName Aapex
skinparam backgroundColor white
skinparam minClassWidth 155
skinparam nodesep 34
skinparam ranksep 70

skinparam component {
BorderColor 007BFF
ArrowColor 007BFF
BackgroundColor white
}

skinparam interface {
BorderColor 007BFF
ArrowColor 007BFF
}

header Wallet Architecture
title
Wallet Architecture
end title

frame "wallet-backend" #AliceBlue {
  interface "High-level APIs" as API
  [Wallet Backend] as WB
  [Verifier Backend] as VB
  [Issuer Backend] as IB
  [Wallet Context Manager] as WCTX
}

frame "SSI Kit" #Azure {
  [SSI Kit Context] as SCTX
  [Custodian] as CU
  [Signatory] as SI
  [Auditor] as AU
}

database "Data store" #WhiteSmoke {
  frame "User Stores" {
    [User Store (A)] as USA
  }
  [Issuer Store] as IS
  [Verifier Store] as VS
}

() "Web wallet (UI)" -- API
() "Issuer portal (UI)" -- API
() "Verifier portal (UI)" -- API

API -- WB
API -- IB
API -- VB

WB -- WCTX
IB -- WCTX
VB -- WCTX

WCTX -- SCTX

SCTX -- CU
SCTX -- AU
SCTX -- SI

SI -- IS
AU -- VS
CU -- USA

@enduml